### ISSUE TITLE
Fails if no password given for ssh-key

### ISSUE THREAD

**Issue by vills** [coderanger/kitchen-sync#1]
On OS X.
If my ~/.ssh/id_rsa protected by password and i didn't provide it to system keychain, than action 'converge' fails (sure, all another actions will fails to) with exception:
```
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [undefined method `to_blob' for nil:NilClass]
````

Problem is here: `kitchen-sync-1.0.1/lib/kitchen-sync/rsync.rb:47:in 'copy_identity'`, because of `Net::SSH::Authentication::Agent.connect.identities.first` returns `nil`.

I'm sure, gem should check this situation.

**Comment by coderanger** [comment]
This is documented in the README. The key must be loaded in to your SSH agent meaning it is already decrypted.
