### ISSUE TITLE
rsync for TK 1.4

### ISSUE THREAD

**Issue by bottkv488** [coderanger/kitchen-sync#13]
Hi,
is there a roadmap for making rsync transport available for TK 1.4?
This would be awesome, as some of us
*) have to use TK 1.4
*) run into idempotence issues using sftp transport mode

Thank you very much for your effort!

**Comment by vills** [comment]
+1

**Comment by coderanger** [comment]
This is now live as part of 2.0.

**Comment by bottkv488** [comment]
@coderanger,
This saved my day :)

**Comment by vills** [comment]
Leave it here just for history:
There is another method to use rsync in TK 1.4+: https://github.com/unibet/kitchen-transport-rsync
