### ISSUE TITLE
Kitchen-Sync 2.x breaks inspec verifier

### ISSUE THREAD

**Issue by rhass-r7** [coderanger/kitchen-sync#14]
Kitchen throws an unsupported error/backtrace when when using the `inspec` verifier.

Given inspec does most of the testing via ssh and winrm, the expected behavior is to fallback to the default transport during the verify phases.

```
I, [2016-01-14T10:19:45.257667 #19153]  INFO -- Kitchen: -----> Starting Kitchen (v1.4.2)
I, [2016-01-14T10:19:45.857382 #19153]  INFO -- Kitchen: -----> Verifying <console-ubuntu-1404>...
D, [2016-01-14T10:19:45.859733 #19153] DEBUG -- Kitchen: ------Exception-------
D, [2016-01-14T10:19:45.859799 #19153] DEBUG -- Kitchen: Class: Kitchen::ActionFailed
D, [2016-01-14T10:19:45.859868 #19153] DEBUG -- Kitchen: Message: Failed to complete #verify action: [Verifier rsync]
D, [2016-01-14T10:19:45.859937 #19153] DEBUG -- Kitchen: ---Nested Exception---
D, [2016-01-14T10:19:45.860004 #19153] DEBUG -- Kitchen: Class: Kitchen::UserError
D, [2016-01-14T10:19:45.860070 #19153] DEBUG -- Kitchen: Message: Verifier rsync
D, [2016-01-14T10:19:45.860136 #19153] DEBUG -- Kitchen: ------Backtrace-------
D, [2016-01-14T10:19:45.860202 #19153] DEBUG -- Kitchen:  does not support the rsync Transport
D, [2016-01-14T10:19:45.860268 #19153] DEBUG -- Kitchen: ----------------------
```

I should note, I have no idea if 1.x works with this or not -- but I would have to assume its not applicable as inspec I believe needs a newer version of test-kitchen which may not be fully supported by kitchen-sync 1.x anyway.

**Comment by coderanger** [comment]
Nothing I can do about it, they hardcode the list of allowed transports: https://github.com/chef/kitchen-inspec/blob/master/lib/kitchen/verifier/inspec.rb#L38-L49

**Comment by rhass-r7** [comment]
Bummer... I can open an issue against inspec and we can close this if you want.

**Comment by coderanger** [comment]
I'm okay with leaving it open for others to find since I'm sure this won't be the last.

**Comment by rhass-r7** [comment]
Opened [kitchen-inspec Issue-#31](https://github.com/chef/kitchen-inspec/issues/31).

**Comment by coderanger** [comment]
Pull request for it is in, but it is after work hours in Germany so probably won't see it until tomorrow.

**Comment by coderanger** [comment]
Never mind, they are awesome and merged it. Closing this out as it will work in the next release of `kitchen-inspec`.
