### ISSUE TITLE
allow dual posix/windows test-kitchen use

### ISSUE THREAD

**Issue by troyready** [coderanger/kitchen-sync#17]
A small enhancement would make this awesome plugin even better:

Would it be possible to rebase the [init_command monkey patching](https://github.com/coderanger/kitchen-sync/blob/master/lib/kitchen-sync/core_ext.rb#L22-L24) off the [powershell conditional](https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/shell.rb#L54-L72) in the upstream test-kitchen gem? As it stands now, the `mkdir -p` command is being executed on windows platforms even when they aren't using the kitchen-sync transports.

I tested this by just copying over the upstream init_command code and removing the `rm -rf` part. Would be happy to open a pull request along these lines.

**Comment by coderanger** [comment]
What I should probably do is check if `instance.transport.is_a?` for my two classes and if not just delegate to `super`.

**Comment by scopenco** [comment]
+1
This problem really annoying, especially when you have suites on linux and windows in one testkitchen env.
