### ISSUE TITLE
kitchen-sync destroys files dropped by cookbooks to Chef::Config[:file_cache_path]

### ISSUE THREAD

**Issue by rhass-r7** [coderanger/kitchen-sync#3]
I observed an odd behavior in which a remote_file call in a cookbook I was developing, was constantly redownloading the file despite having a valid checksum defined in the call to the resource. On a hunch, I disabled kitchen-sync and ran kitchen converge once more, and discovered the file did not redownload.

I am not sure what the best way to handle this is, as I suspect kitchen-sync should in most cases clear our the Chef::Config[:file_cache_path] contents... the only idea I have at the moment is to have a white-list of files, but that seems somewhat kludgy and can be problematic to maintain.

**Comment by obazoud** [comment]
To avoid this kind of behaviour, pre install rsync.

**Comment by coderanger** [comment]
Hmm, unless your file cache path is being updated by kitchen that seems odd. Generally kitchen only transfers stuff under /tmp/kitchen.

**Comment by coderanger** [comment]
Closing this out as not reproducible.

**Comment by lcosmes** [comment]
This can be reproduced when using kitchen-sync, the Jira community cookbook (https://supermarket.chef.io/cookbooks/jira / v2.7.0 or later), the ark community cookbook (https://github.com/burtlo/ark/ / v0.8.2 or later).  You can run the Jira install with all default attributes, except for default['jira']['install_type'] = 'standalone'  The Jira tarball gets downloaded every time you run test kitchen as the contents of /tmp/kicthen/cache get wiped out.

**Comment by coderanger** [comment]
@lcosmes Which transport are you using?

**Comment by lcosmes** [comment]
@coderanger :
transport:
  name: sftp

Let me know if you need more info.

**Comment by coderanger** [comment]
@lcosmes Try out the version I just pushed to master, should be better.

**Comment by lcosmes** [comment]
@coderanger I tested your latest changes using sftp transport and the contents of the cache directory were not removed this time around!  Thanks for the quick fix as this plugin really speeds up development.
