### ISSUE TITLE
Support ssh_gateway like ssh transport

### ISSUE THREAD

**Issue by atheiman** [coderanger/kitchen-sync#34]
This gem is awesome! Im kitchen testing _lots_ of nodes in ec2 and it has dropped my initial converge time from 2 min / node to about 30 sec / node!

It doesnt seem it supports ssh_gateway config like the ssh transport does: https://github.com/test-kitchen/test-kitchen/blob/v1.18.0/lib/kitchen/transport/ssh.rb#L360-L378

I think one of the best use cases for this gem is kitchen tests in cloud providers (ssh transport to a vagrant box is already fast), and most of these setups use a bastion host and private ip'd hosts in a private subnet.

Could this be implemented?

**Comment by atheiman** [comment]
lol this totally works, i just used it.

**Comment by coderanger** [comment]
The SFTP plugin is built on top of the core SSH implementation so anything that works in core should work there. For `rsync`, it opens its own connection so all bets are off.

**Comment by atheiman** [comment]
One thing i want to take advantage of in Net::SFTP is its ability to list files in the remote filesystem, specifically with wildcards. I opened a pr for it #35
