### ISSUE TITLE
Isn't used when uploading busser things?

### ISSUE THREAD

**Issue by jordansissel** [coderanger/kitchen-sync#7]
Using the rsync busser, I see this:

```
% KITCHEN_SYNC_MODE=Rsync kitchen verify
-----> Starting Kitchen (v1.3.1)
-----> Verifying <whoa-centos-70>...
       Removing /tmp/busser/suites/rspec
       Uploading /tmp/busser/suites/rspec/bin/pleaserun (mode=0755)
       Uploading /tmp/busser/suites/rspec/CHANGELOG.asciidoc (mode=0644)
       Uploading /tmp/busser/suites/rspec/examples/runit.rb (mode=0644)
       Uploading /tmp/busser/suites/rspec/Gemfile (mode=0644)
```

Seems like it's uploading with the normal (slow) uploader.

I haven't done any digging to figure out why. Doing `kitchen provision` uploads assets with rsync, though.

**Comment by nvtkaszpir** [comment]
I have found that it does not work with parameters from env vars.

To fix this, add to .kitchen.yml in transport section new field named 'name:'

```yaml
transport:
  name: rsync
```

looks like this is an issue with test-kitchen 1.4.x

**Comment by iiro** [comment]
Hmm. I'm getting this if I try to run converge with the above config in .kitchen.yml:

-----> Starting Kitchen (v1.4.2)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'rsync' transport from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

--

kitchen-sync is:

 # chef gem list|grep kitchen-sync
kitchen-sync (1.1.1)


Should that work with TK 1.4.2...?

**Comment by nvtkaszpir** [comment]
You also need kitchen-transport-rsync in Gemfile

**Comment by coderanger** [comment]
Handled with the new plugin stuffs.
