### ISSUE TITLE
It doesn't initialize kitchen-sync with kitchen version 1.4.x

### ISSUE THREAD

**Issue by lbosque** [coderanger/kitchen-sync#9]
The require correctly loads the gem but after that it doesn't seem to call even the kitchen-sync initializer.
Needed to downgrade kitchen to 1.3.1.

**Comment by coderanger** [comment]
That is because in 1.4 it is swapped to be a transport plugin instead. Some monkeypatching is still needed which I'm trying to resolve before a real release but master does have working SFTP incremental transfers on 1.4.
